### ISSUE TITLE
Do you no longer use fast refiling with hydra anymore?

### ISSUE THREAD

**Issue by rieje** [mm--/dot-emacs#1]
I came across [this post of yours](https://mollermara.com/blog/Fast-refiling-in-org-mode-with-hydras/) and while you posted a gist of the relevant code, I don't see it anywhere in your org config. Do you not use it any more? Curious if the workflow you've had had changed over time and what your current workflow is like now that it seems you no longer use it anymore.

**Comment by mm--** [comment]
Hey there! Yes, I actually do still use hydras for fast refiling. I use it almost every day. My configuration for it though is loaded in a separate file (see [how I load personal files](https://github.com/mm--/dot-emacs/blob/08821dc490d2751cce249a363fe84b2b55a68619/init.el#L34)) that's not committed to Github mostly because it contains a bunch of personal org-mode headlines and such. I suppose I should move the hydra-refiling functions to my org config and just keep my personally specific configs in my personal file.

**Comment by rieje** [comment]
Cool. I see alphapapa also shared `ap/org-agenda-current-subtree-or-region` that you use. Can you tell me how this is useful? I'm still new to `org-agenda`--when would this be useful? As far as I understand, you can `C-c C-w` to file results of `org-agenda` but how is this faster or more efficient than regular refiling in an org file?

Lastly, do you use alphapapa's  [org-super-agenda](https://github.com/alphapapa/org-super-agenda) or have any thoughts on it? If I understand correctly, the contents of `org-agenda` are sorted by: any headlines with set dates (schedule/deadline), then any filtered tasks in the order of `org-agenda-files`, and also taking into account priorities, etc. It seems `org-super-agenda` is just strictly better because it allows the user to customize how items should be grouped, sorted, and displayed, while still taking into account daily/weekly aspect of `org-agenda`, but I wonder if I should get to know `org-agenda` well befire I start using `org-super-agenda`.

**Comment by mm--** [comment]
The nice thing about alphapapa's function is that you can take some org buffer selection and get it into an agenda. From there, you can do neat things like filtering on tags or regular expressions, etc. But in this case it's useful because you can mark headings with `m` and perform "bulk actions" on these marked headings with `B`, similar to how you'd perform a bunch of actions to marked files in `dired`. Normally the only bulk action I do is bulk archiving (`B $`), but it's also useful here for bulk refiling (`B r`). This is fast because you only have to select the refile target once for *all* marked headings.

I haven't used `org-super-agenda` yet, but I've been meaning to get around to it. `org-agenda` is customizable enough that you can *technically* control sorting, but it's very slow and kind of a pain to implement. I have an example of sorting "next actions" by their age [here](https://github.com/mm--/dot-emacs/blob/master/jmm-org-config.org#sorting-timestamps-in-the-agenda), but again it's quite slow. Grouping is also possible, but alphapapa is right in that you lose date information. I think one of the cool things about `org-super-agenda` is its really clean specification of how to group and filter in an agenda. It seems way nicer than what I'm doing now, which is to define a bunch of elisp `org-agenda-skip-function`'s. I suspect it'll be a better experience for you if you use `org-super-agenda` first, and only if you find there's something you can't do, possibly use normal `org-agenda`'s instead. And depending on what kind of agendas you use you can almost certainly use both simultaneously.

My main problem with my agenda right now isn't so much grouping or layout as much as speed. My agenda is painfully slow to generate. This is because I (1) have a lot of org-mode headings and (2) use custom functions with `org-agenda-prefix-format` to display interesting statistics (like the "age" of a task) next to headings. Also (3), when org-agendas are regenerated, there's very little in terms of caching. It just goes through all your files without knowing exactly what changed. Alphapapa [experimented a while ago](https://github.com/alphapapa/org-agenda-ng) with a different way to generate agendas, with the hope of increasing speed, but apparently it didn't pan out. When I need to quickly find things, I'll use his `helm-org-rifle`. On my phone, [orgzly](https://github.com/orgzly/orgzly-android) is pretty nice here because searches are done with a generated database instead of parsing each time. John Kitchin seems to [do a similar thing](http://kitchingroup.cheme.cmu.edu/blog/2017/01/03/Find-stuff-in-org-mode-anywhere/) where he saves org headings in `sqlite`. I might have to move to something like that eventually.

Anyway, sorry for the wall of text and late reply. Hope that helps though.

**Comment by rieje** [comment]
Would it be trivial to alter [the code](https://gist.github.com/mm--/60e0790bcbf8447160cc87a66dc949ab) such that you don't need to create a separate function for each file you want to refile to? I'm curious why something like a list of files or an array isn't used (disclaimer, I'm a complete noob). For someone with a dozen files, a dozen functions that do the same thing need to be defined and it seems a little weird to need to scale the number of functions to the number of files you want to refile to. Since you used macro to clean up the code, perhaps you've already considered this and it would not be worthwhile to attempt to further improve the code. 

Also, is there a reason you didn't restrict the keybinding to orgmode map?

**Comment by mm--** [comment]
It's been a while since I looked at it, but I think defining subhydras automatically makes new functions. I'm not sure of a way around that, or if it even incurs a performance cost worth worrying about. I don't have too many files to refile to, so it doesn't seem to be much of an issue for me. What *is* an issue lately is that sometimes my categories don't match up with my filenames. For example, "calendar events" might be in one of many files, depending on what event it is. I'm thinking a better way to specify refile locations is to use headline UUIDs instead of file+headline name.

I'm not exactly sure, but I might have made it a global keybinding (instead of a org-mode-map binding) because I wanted it to work in `org-agenda-mode`. I guess one could make bindings for just those two modes, but I haven't really needed to use `<f9> r` for anything else yet.
